[build]
  command = "npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"


[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
